package com.example.bookshop.data.struct;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;

@Getter
@Setter
@ToString(of = "name")
@Entity
@Table(name = "author")
@ApiModel(description = "data model of author entity")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db", position = 1)
    private Integer id;

    @Column(columnDefinition = "text")
    @ApiModelProperty(position = 3)
    private String description;

    @ApiModelProperty(position = 2)
    private String name;

    private String photo;
    private String slug;

}
